sudo: false
language: rust
rust:
- stable
- 1.10.0
- beta
- nightly
matrix:
  include:
    - rust: stable
      env: CARGOFLAGS=--features="serialize"
    - rust: stable
      env: CARGOFLAGS=--features="std"
    - rust: stable
      env: CARGOFLAGS=--features="std serialize"
    - rust: nightly
      env: CARGOFLAGS=--features="serialize use-intrinsics"
branches:
  except:
  - gh-pages
script:
- cargo test $CARGOFLAGS
