language: rust
rust:
  - stable
  - 1.5.0
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: FEATURES=--features use-intrinsics
branches:
  except:
    - gh-pages
script:
  - cargo test --verbose $FEATURES