os:
- linux
- windows
sudo: false
language: rust
rust:
- stable
- 1.27.0
- beta
- nightly
matrix:
  include:
    - rust: stable
      env: CARGOFLAGS="--features serde"
    - rust: stable
      env: CARGOFLAGS="--features std"
    - rust: stable
      env: CARGOFLAGS="--features std,serde"
    - rust: nightly
      env: CARGOFLAGS=--all-features

    - rust: stable
      os: windows
      env: CARGOFLAGS="--features serde"
    - rust: stable
      os: windows
      env: CARGOFLAGS="--features std"
    - rust: stable
      os: windows
      env: CARGOFLAGS="--features std,serde"
    - rust: nightly
      os: windows
      env: CARGOFLAGS=--all-features
branches:
  except:
  - gh-pages
script:
- cargo test $CARGOFLAGS
