[package]
name = "half"
version = "1.0.0"
authors = ["Kathryn Long <squeeself@gmail.com>"]
description = "Half-precision floating point f16 type for Rust implementing the IEEE 754-2008 binary16 type."
repository = "https://github.com/starkat99/half-rs.git"
homepage = "https://github.com/starkat99/half-rs"
documentation = "http://starkat99.github.io/half-rs/half/"
readme = "README.md"
keywords = ["f16", "no_std"]
license = "MIT/Apache-2.0"

[features]
std = []
use-intrinsics = []
serialize = ["serde", "serde_derive"]

[dependencies]
serde = { version = "0.9", optional = true }
serde_derive = { version = "0.9", optional = true }