[package]
name = "half"
# Remember to keep in sync with html_root_url crate attribute
version = "1.7.1"                                                                                                                              # Remember to keep in sync with html_root_url crate attribute                                                                                                                           # Remember to keep in sync with html_root_url crate attribute
authors = ["Kathryn Long <squeeself@gmail.com>"]
description = "Half-precision floating point f16 and bf16 types for Rust implementing the IEEE 754-2008 standard binary16 and bfloat16 types."
repository = "https://github.com/starkat99/half-rs"
readme = "README.md"
keywords = ["f16", "bfloat16", "no_std"]
license = "MIT OR Apache-2.0"
categories = ["no-std", "data-structures", "encoding"]
edition = "2018"
exclude = ["/ci", "/*.yml"]

[badges]
maintenance = { status = "passively-maintained" }

[features]
std = ["alloc"]
use-intrinsics = []
serialize = ["serde"] # Deprecated. Use serde directly.
alloc = []

[dependencies]
bytemuck = { version = "1.4.1", default-features = false, features = [
    "derive",
], optional = true }
serde = { version = "1.0", default-features = false, features = [
    "derive",
], optional = true }
num-traits = { version = "0.2.14", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
rand = "0.7"
version-sync = "0.8"

[[bench]]
name = "convert"
harness = false

[package.metadata.docs.rs]
features = ["std", "serde", "bytemuck", "num-traits"]
